//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public Accessory()
        {
            this.ProviderAccessory = new HashSet<ProviderAccessory>();
            this.RepairAccessory = new HashSet<RepairAccessory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public long Amount { get; set; }
    
        public virtual ICollection<ProviderAccessory> ProviderAccessory { get; set; }
        public virtual ICollection<RepairAccessory> RepairAccessory { get; set; }
    }
}
