//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Order = new HashSet<Order>();
            this.Repair = new HashSet<Repair>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Code { get; set; }
        public string Identification { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TipoVehiculo { get; set; }
        public string Placa { get; set; }
        public string ModeloVehiculo { get; set; }
        public string ColorVehiculo { get; set; }
        public Nullable<long> TipoCliente { get; set; }
        public string Observaciones { get; set; }
        public Nullable<long> ServiceId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Repair> Repair { get; set; }
    }
}
