//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MechanicOrder
    {
        public long Id { get; set; }
        public long IdOrder { get; set; }
        public long IdMechanic { get; set; }
        public long IsPrincipal { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Mechanic Mechanic { get; set; }
    }
}
