//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.MechanicOrder = new HashSet<MechanicOrder>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdClient { get; set; }
        public string Code { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public long Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<MechanicOrder> MechanicOrder { get; set; }
    }
}
