//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderAccessory
    {
        public long Id { get; set; }
        public long IdProvider { get; set; }
        public long IdAccessory { get; set; }
        public System.DateTime Date { get; set; }
        public long Amount { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Accessory Accessory { get; set; }
    }
}
