//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.ProviderAccessory = new HashSet<ProviderAccessory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<ProviderAccessory> ProviderAccessory { get; set; }
    }
}
