//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Client = new HashSet<Client>();
            this.Mechanic = new HashSet<Mechanic>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public double NormalPrice { get; set; }
        public double PreferentialPrice { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<Mechanic> Mechanic { get; set; }
    }
}
