//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using Entities;
namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class workshopEntities : DbContext
    {
        public workshopEntities()
            : base("name=workshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Mechanic> Mechanic { get; set; }
        public DbSet<MechanicOrder> MechanicOrder { get; set; }
        public DbSet<Accessory> Accessory { get; set; }
        public DbSet<Provider> Provider { get; set; }
        public DbSet<ProviderAccessory> ProviderAccessory { get; set; }
        public DbSet<RepairAccessory> RepairAccessory { get; set; }
        public DbSet<Repair> Repair { get; set; }
    }
}
